language: node_js
node_js: 6
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    packages:
    - gdebi
    - oracle-java8-installer
    - oracle-java8-set-default
script:
  - npm run test
