language: node_js
node_js: 6
dist: trusty
sudo: required
before_script:
- npm run test:lint:js
- npm run test:lint:wc
script:
- xvfb-run wct
- if [ "$TRAVIS_BRANCH" == "master" ]; then frauci-update-version; fi
env:
  global:
  - REPO_NAME=d2l-upcoming-assessments-ui
  - secure: "Hl4hi1duWW0V7MboF9iY5YrZrpPAjC0cKr5aylylwzm2x9ybOLK82CU/CH2rrYb/fhHvgSfz6bUfGaRRjzTys+m/Z/7l+sge1XOoYGWHLELfZaQvzrEOlp7QRlrsAa8Y1elGTKNRi0Vbw6PNfNMVClD7aWTf8nDZ2j2jM+E6gPzolDnkiOa8Ne+OZFXz+oNUklkzv3karWDixXHywl9nACcRkN3mo6oKb5D4Qr4eEKK+JZYnH46DZI22UqW6rzZSuzcQFlhZxbHVfvqbrQIcTnHHJSA0XUB9fhkRgJxnjn0xvzfhldB5BTU6yzh4WPIHfz8bDpC9QpCqtj8q1Q3ve+n/0nWIR/6+BbgIJTNZWIh8xXKPexlp5AKfTPOD6tWchTM3CPnzT77HtiY8jJBaIYMkEMr3/XS3hcrI4Tl95xD25w29cBZ8Gs08n0TrLKEFcdZUelRlk9JjXitGIMriwspLrVRuCZWZB+4lPuaGbj7t9U+UuVAGQQT00dBTqzd+SjH+4ICcPR48mI6cmDshSiir2tA0Dmdw6j2jgmE4dlqGlVAEpLiYxO8DeFTBp2EJP7PsLWTn+5cfqKv0pRsf3lU/kwdr2vdDYl4rl7kWmMM/gCmEkrnYgNs0TM+Sq8dLqLDQxNkPIe1IRWXWb2QNN635O5SaBgRun982EP2slfY="
addons:
  firefox: latest
  apt:
    packages:
    - gdebi
    - oracle-java8-installer
    - oracle-java8-set-default
